SRC_FILES := usb_bsp.c usbh.c connect_usb.c
SRC_FILES += STM32_USB_OTG_Driver/src/usb_core.c STM32_USB_OTG_Driver/src/usb_hcd.c STM32_USB_OTG_Driver/src/usb_hcd_int.c

include $(KERNEL_ROOT)/compiler.mk
