SRC_FILES += altcp_alloc.c \
		     altcp_tcp.c \
			 altcp.c \
			 def.c \
			 dns.c \
			 inet_chksum.c \
			 init.c \
			 ip.c \
			 mem.c \
			 memp.c \
			 netif.c \
			 pbuf.c \
			 raw.c \
			 stats.c \
			 sys.c \
			 tcp_in.c \
			 tcp_out.c \
			 tcp.c \
			 timeouts.c \
			 udp.c

SRC_DIR += ipv4

include $(KERNEL_ROOT)/compiler.mk
